### ISSUE TITLE
Feature suggestion: capture and restore fixtures

### ISSUE THREAD

**Issue by neboskreb** [gofabian/junit-fixture-extension#1]
The suggested feature should improve the point which receives most criticism about fixtures: the lack of determinism.

The problem is that fixture libraries are based on the concept of ‘constrained non-determinism’, i.e. they generate the test data in a sensible but still random way. This makes debugging hard: once a test fails, the next time you run it you don't get the same data that broke it.

The idea is to capture the generated fixtures before test for the case it fails and store them in some way/shape/form. This way, when the developer needs to re-run the test he could load those exact fixtures which caused the failure. Once the bug is fixed, the generation of fixtures resumed.

In case of success, the captured fixtures are discarded.

I suggest help in implementing this feature if you're interested. What do you think? 

Contact me at neboskreb/@/ya.ru 
John

**Comment by gofabian** [comment]
I do not plan to implement anything like that, but I appreciate any discussion. If you would like to consider yourself responsible to push this topic, feel free to suggest a solution. Else this issue is likely to be closed in future.

**Comment by neboskreb** [comment]
I needed this functionality almost a year ago. That moment I could get budget allocated for it, thus solving my problem AND contributing to the community, but having received no reply I went with a dirty one-time patch solving my immediate task. So it's off the table. Sorry bro!

**Comment by gofabian** [comment]
That is ok for me. As this is a small private project I do not guarantee any support. Especially for commercial projects. 

Thanks for your feedback.
